window.CK_DATA = (() => {
  const STORES = [
    {
      id: "bargain",
      name: "Bargain Basket",
      kind: "Discount grocer",
      mapsQuery: "Aldi grocery",
      blurb: "Best on staples, produce, and store-brand proteins.",
    },
    {
      id: "value",
      name: "SuperValue",
      kind: "Big-box grocery",
      mapsQuery: "Walmart Supercenter grocery",
      blurb: "Broadest shelf. Strong when Bargain Basket is missing an item.",
    },
    {
      id: "harbor",
      name: "Harbor Market",
      kind: "Neighborhood supermarket",
      mapsQuery: "Kroger",
      blurb: "Sales and meat counter. Use when you need a conventional supermarket.",
    },
    {
      id: "grove",
      name: "Grove & Vine",
      kind: "Premium grocer",
      mapsQuery: "Whole Foods Market",
      blurb: "Highest prices. Only worth it if you specifically want this store.",
    },
  ];

  const INGREDIENTS = {
    oats: { name: "Rolled oats", unit: "lb", pack: 1, category: "Grains", pantry: "staples", prices: { bargain: 1.19, value: 1.48, harbor: 1.89, grove: 3.49 } },
    rice: { name: "Long-grain rice", unit: "lb", pack: 1, category: "Grains", pantry: "staples", prices: { bargain: 0.78, value: 0.98, harbor: 1.29, grove: 2.49 } },
    pasta: { name: "Dry pasta", unit: "lb", pack: 1, category: "Grains", pantry: "staples", prices: { bargain: 0.89, value: 1.00, harbor: 1.29, grove: 1.99 } },
    bread: { name: "Sandwich bread", unit: "loaf", pack: 1, category: "Grains", prices: { bargain: 1.35, value: 1.78, harbor: 2.49, grove: 3.99 } },
    tortillas: { name: "Flour tortillas", unit: "pack", pack: 1, category: "Grains", prices: { bargain: 1.45, value: 1.98, harbor: 2.49, grove: 3.79 } },
    flour: { name: "All-purpose flour", unit: "lb", pack: 2, category: "Grains", pantry: "staples", prices: { bargain: 0.52, value: 0.62, harbor: 0.79, grove: 1.29 } },
    eggs: { name: "Eggs", unit: "each", pack: 12, category: "Dairy", pantry: "fridge", prices: { bargain: 0.22, value: 0.28, harbor: 0.33, grove: 0.5 } },
    milk: { name: "Milk", unit: "gal", pack: 1, category: "Dairy", pantry: "fridge", prices: { bargain: 2.69, value: 3.14, harbor: 3.49, grove: 5.49 } },
    yogurt: { name: "Plain yogurt", unit: "oz", pack: 32, category: "Dairy", prices: { bargain: 0.08, value: 0.1, harbor: 0.12, grove: 0.18 } },
    cheddar: { name: "Cheddar", unit: "lb", pack: 0.5, category: "Dairy", prices: { bargain: 2.48, value: 3.28, harbor: 3.98, grove: 6.49 } },
    butter: { name: "Butter", unit: "lb", pack: 1, category: "Dairy", pantry: "oils", prices: { bargain: 2.89, value: 3.48, harbor: 3.99, grove: 6.49 } },
    chickenThigh: { name: "Chicken thighs", unit: "lb", pack: 1, category: "Meat", prices: { bargain: 1.79, value: 2.19, harbor: 2.49, grove: 4.99 } },
    chickenBreast: { name: "Chicken breast", unit: "lb", pack: 1, category: "Meat", prices: { bargain: 2.49, value: 2.99, harbor: 3.49, grove: 6.99 } },
    groundBeef: { name: "Ground beef 85%", unit: "lb", pack: 1, category: "Meat", prices: { bargain: 3.49, value: 3.97, harbor: 4.49, grove: 7.49 } },
    groundTurkey: { name: "Ground turkey", unit: "lb", pack: 1, category: "Meat", prices: { bargain: 2.89, value: 3.29, harbor: 3.79, grove: 6.49 } },
    sausage: { name: "Smoked sausage", unit: "lb", pack: 1, category: "Meat", prices: { bargain: 2.49, value: 2.98, harbor: 3.49, grove: 5.99 } },
    tuna: { name: "Canned tuna", unit: "can", pack: 1, category: "Meat", prices: { bargain: 0.79, value: 0.98, harbor: 1.19, grove: 2.29 } },
    onion: { name: "Yellow onion", unit: "each", pack: 1, category: "Produce", pantry: "produce", prices: { bargain: 0.62, value: 0.78, harbor: 0.99, grove: 1.29 } },
    garlic: { name: "Garlic head", unit: "each", pack: 1, category: "Produce", pantry: "produce", prices: { bargain: 0.45, value: 0.58, harbor: 0.79, grove: 0.99 } },
    carrot: { name: "Carrots", unit: "lb", pack: 1, category: "Produce", prices: { bargain: 0.72, value: 0.88, harbor: 1.19, grove: 1.79 } },
    celery: { name: "Celery", unit: "bunch", pack: 1, category: "Produce", prices: { bargain: 1.19, value: 1.48, harbor: 1.79, grove: 2.49 } },
    broccoli: { name: "Broccoli", unit: "lb", pack: 1, category: "Produce", prices: { bargain: 1.29, value: 1.68, harbor: 1.99, grove: 2.99 } },
    spinach: { name: "Baby spinach", unit: "oz", pack: 8, category: "Produce", prices: { bargain: 0.22, value: 0.28, harbor: 0.32, grove: 0.45 } },
    pepper: { name: "Bell pepper", unit: "each", pack: 1, category: "Produce", prices: { bargain: 0.78, value: 0.98, harbor: 1.29, grove: 1.79 } },
    tomato: { name: "Tomatoes", unit: "lb", pack: 1, category: "Produce", prices: { bargain: 1.19, value: 1.48, harbor: 1.79, grove: 2.99 } },
    potato: { name: "Russet potatoes", unit: "lb", pack: 1, category: "Produce", prices: { bargain: 0.58, value: 0.68, harbor: 0.89, grove: 1.49 } },
    cabbage: { name: "Green cabbage", unit: "each", pack: 1, category: "Produce", prices: { bargain: 1.29, value: 1.68, harbor: 2.19, grove: 2.99 } },
    banana: { name: "Bananas", unit: "each", pack: 1, category: "Produce", prices: { bargain: 0.19, value: 0.23, harbor: 0.28, grove: 0.39 } },
    apple: { name: "Apples", unit: "each", pack: 1, category: "Produce", prices: { bargain: 0.48, value: 0.62, harbor: 0.79, grove: 1.29 } },
    lemon: { name: "Lemon", unit: "each", pack: 1, category: "Produce", pantry: "produce", prices: { bargain: 0.42, value: 0.58, harbor: 0.69, grove: 0.89 } },
    cannedTomato: { name: "Canned tomatoes", unit: "can", pack: 1, category: "Pantry", pantry: "staples", prices: { bargain: 0.79, value: 0.98, harbor: 1.19, grove: 1.99 } },
    frozenVeg: { name: "Frozen mixed vegetables", unit: "lb", pack: 1, category: "Frozen", prices: { bargain: 0.98, value: 1.18, harbor: 1.48, grove: 2.49 } },
    blackBeans: { name: "Canned black beans", unit: "can", pack: 1, category: "Pantry", pantry: "staples", prices: { bargain: 0.72, value: 0.88, harbor: 1.09, grove: 1.49 } },
    lentils: { name: "Dry lentils", unit: "lb", pack: 1, category: "Pantry", pantry: "staples", prices: { bargain: 1.09, value: 1.28, harbor: 1.59, grove: 2.29 } },
    chickpeas: { name: "Canned chickpeas", unit: "can", pack: 1, category: "Pantry", prices: { bargain: 0.72, value: 0.88, harbor: 1.09, grove: 1.49 } },
    peanutButter: { name: "Peanut butter", unit: "oz", pack: 16, category: "Pantry", pantry: "staples", prices: { bargain: 0.12, value: 0.16, harbor: 0.19, grove: 0.31 } },
    salsa: { name: "Salsa", unit: "oz", pack: 16, category: "Pantry", prices: { bargain: 0.09, value: 0.12, harbor: 0.15, grove: 0.24 } },
    broth: { name: "Chicken broth", unit: "oz", pack: 32, category: "Pantry", prices: { bargain: 0.04, value: 0.05, harbor: 0.07, grove: 0.12 } },
    oliveOil: { name: "Olive oil", unit: "oz", pack: 17, category: "Oils", pantry: "oils", prices: { bargain: 0.18, value: 0.24, harbor: 0.28, grove: 0.45 } },
    vegOil: { name: "Vegetable oil", unit: "oz", pack: 48, category: "Oils", pantry: "oils", prices: { bargain: 0.06, value: 0.08, harbor: 0.1, grove: 0.16 } },
    sesameOil: { name: "Sesame oil", unit: "oz", pack: 5, category: "Oils", pantry: "oils", prices: { bargain: 0.38, value: 0.48, harbor: 0.55, grove: 0.79 } },
    soy: { name: "Soy sauce", unit: "oz", pack: 15, category: "Condiments", pantry: "sauces", prices: { bargain: 0.08, value: 0.1, harbor: 0.13, grove: 0.22 } },
    vinegar: { name: "Vinegar", unit: "oz", pack: 16, category: "Condiments", pantry: "sauces", prices: { bargain: 0.05, value: 0.07, harbor: 0.09, grove: 0.14 } },
    hotSauce: { name: "Hot sauce", unit: "oz", pack: 5, category: "Condiments", pantry: "sauces", prices: { bargain: 0.22, value: 0.28, harbor: 0.34, grove: 0.5 } },
    ketchup: { name: "Ketchup", unit: "oz", pack: 20, category: "Condiments", pantry: "sauces", prices: { bargain: 0.08, value: 0.1, harbor: 0.13, grove: 0.2 } },
    salt: { name: "Salt", unit: "oz", pack: 26, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.03, value: 0.04, harbor: 0.05, grove: 0.08 } },
    blackPepper: { name: "Black pepper", unit: "oz", pack: 3, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.42, value: 0.55, harbor: 0.7, grove: 1.1 } },
    garlicPowder: { name: "Garlic powder", unit: "oz", pack: 3, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.35, value: 0.48, harbor: 0.62, grove: 0.95 } },
    cumin: { name: "Cumin", unit: "oz", pack: 2, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.48, value: 0.62, harbor: 0.8, grove: 1.2 } },
    chiliPowder: { name: "Chili powder", unit: "oz", pack: 3, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.32, value: 0.42, harbor: 0.55, grove: 0.85 } },
    paprika: { name: "Paprika", unit: "oz", pack: 2, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.4, value: 0.55, harbor: 0.7, grove: 1.05 } },
    italian: { name: "Italian seasoning", unit: "oz", pack: 1, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.7, value: 0.9, harbor: 1.15, grove: 1.6 } },
    cinnamon: { name: "Cinnamon", unit: "oz", pack: 2, category: "Seasonings", pantry: "seasonings", prices: { bargain: 0.38, value: 0.5, harbor: 0.68, grove: 1.05 } },
    sugar: { name: "Sugar", unit: "lb", pack: 4, category: "Pantry", pantry: "staples", prices: { bargain: 0.52, value: 0.62, harbor: 0.75, grove: 1.2 } },
  };

  const PANTRY_GROUPS = [
    {
      id: "seasonings",
      title: "Seasonings",
      items: ["salt", "blackPepper", "garlicPowder", "cumin", "chiliPowder", "paprika", "italian", "cinnamon"],
    },
    {
      id: "oils",
      title: "Oils & fats",
      items: ["oliveOil", "vegOil", "sesameOil", "butter"],
    },
    {
      id: "sauces",
      title: "Sauces",
      items: ["soy", "vinegar", "hotSauce", "ketchup"],
    },
    {
      id: "staples",
      title: "Dry staples",
      items: ["oats", "rice", "pasta", "flour", "sugar", "cannedTomato", "blackBeans", "lentils", "peanutButter"],
    },
    {
      id: "produce",
      title: "Already in the kitchen",
      items: ["onion", "garlic", "lemon"],
    },
    {
      id: "fridge",
      title: "Fridge staples",
      items: ["eggs", "milk"],
    },
  ];

  const RECIPES = [
    {
      id: "oat-bowls",
      name: "Banana oat bowls",
      meal: "breakfast",
      yield: 7,
      minutes: 10,
      cuisines: ["american", "comfort"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "oats", qty: 1.5 },
        { id: "banana", qty: 7 },
        { id: "peanutButter", qty: 7 },
        { id: "cinnamon", qty: 0.2 },
        { id: "milk", qty: 0.25 },
      ],
    },
    {
      id: "egg-toast",
      name: "Eggs on toast",
      meal: "breakfast",
      yield: 7,
      minutes: 15,
      cuisines: ["american"],
      proteins: ["eggs"],
      ingredients: [
        { id: "eggs", qty: 14 },
        { id: "bread", qty: 1 },
        { id: "butter", qty: 0.15 },
        { id: "salt", qty: 0.1 },
        { id: "blackPepper", qty: 0.05 },
      ],
    },
    {
      id: "yogurt-cups",
      name: "Yogurt, apple & peanut butter",
      meal: "breakfast",
      yield: 7,
      minutes: 5,
      cuisines: ["american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "yogurt", qty: 32 },
        { id: "apple", qty: 7 },
        { id: "peanutButter", qty: 7 },
      ],
    },
    {
      id: "breakfast-burritos",
      name: "Egg & bean breakfast burritos",
      meal: "breakfast",
      yield: 7,
      minutes: 30,
      cuisines: ["mexican"],
      proteins: ["eggs", "vegetarian"],
      ingredients: [
        { id: "eggs", qty: 10 },
        { id: "blackBeans", qty: 2 },
        { id: "tortillas", qty: 1 },
        { id: "cheddar", qty: 0.35 },
        { id: "salsa", qty: 8 },
        { id: "onion", qty: 1 },
      ],
    },
    {
      id: "chili",
      name: "Beef & bean chili",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 50,
      cuisines: ["american", "mexican", "comfort"],
      proteins: ["beef"],
      ingredients: [
        { id: "groundBeef", qty: 1 },
        { id: "blackBeans", qty: 2 },
        { id: "cannedTomato", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "chiliPowder", qty: 0.4 },
        { id: "cumin", qty: 0.2 },
        { id: "rice", qty: 0.75 },
      ],
    },
    {
      id: "turkey-chili",
      name: "Turkey chili",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 45,
      cuisines: ["american", "comfort"],
      proteins: ["chicken"],
      ingredients: [
        { id: "groundTurkey", qty: 1 },
        { id: "blackBeans", qty: 2 },
        { id: "cannedTomato", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "chiliPowder", qty: 0.4 },
        { id: "cumin", qty: 0.2 },
        { id: "rice", qty: 0.75 },
      ],
    },
    {
      id: "garlic-chicken-rice",
      name: "Garlic chicken, rice & broccoli",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 35,
      cuisines: ["american", "comfort"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenThigh", qty: 1.75 },
        { id: "rice", qty: 1 },
        { id: "broccoli", qty: 1.5 },
        { id: "garlic", qty: 1 },
        { id: "oliveOil", qty: 1 },
        { id: "paprika", qty: 0.15 },
        { id: "salt", qty: 0.1 },
      ],
    },
    {
      id: "taco-skillet",
      name: "Chicken taco skillet",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 30,
      cuisines: ["mexican"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenThigh", qty: 1.5 },
        { id: "tortillas", qty: 1 },
        { id: "blackBeans", qty: 1 },
        { id: "salsa", qty: 12 },
        { id: "cheddar", qty: 0.35 },
        { id: "cabbage", qty: 0.4 },
        { id: "cumin", qty: 0.15 },
        { id: "chiliPowder", qty: 0.2 },
      ],
    },
    {
      id: "pasta-marinara",
      name: "Pasta marinara with spinach",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 25,
      cuisines: ["italian"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "pasta", qty: 1 },
        { id: "cannedTomato", qty: 2 },
        { id: "garlic", qty: 1 },
        { id: "onion", qty: 1 },
        { id: "spinach", qty: 8 },
        { id: "oliveOil", qty: 1.5 },
        { id: "italian", qty: 0.2 },
      ],
    },
    {
      id: "sausage-pasta",
      name: "Sausage tomato pasta",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 30,
      cuisines: ["italian", "comfort"],
      proteins: ["pork"],
      ingredients: [
        { id: "sausage", qty: 1 },
        { id: "pasta", qty: 1 },
        { id: "cannedTomato", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "italian", qty: 0.2 },
      ],
    },
    {
      id: "lentil-curry",
      name: "Lentil curry bowls",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 40,
      cuisines: ["asian", "comfort"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "lentils", qty: 1 },
        { id: "rice", qty: 1 },
        { id: "cannedTomato", qty: 1 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "carrot", qty: 0.75 },
        { id: "cumin", qty: 0.2 },
        { id: "vegOil", qty: 1 },
      ],
    },
    {
      id: "stir-fry",
      name: "Veggie stir-fry with eggs",
      meal: "dinner",
      yield: 3,
      leftover: "lunch",
      minutes: 20,
      cuisines: ["asian"],
      proteins: ["eggs", "vegetarian"],
      ingredients: [
        { id: "rice", qty: 0.75 },
        { id: "frozenVeg", qty: 1.5 },
        { id: "eggs", qty: 6 },
        { id: "soy", qty: 2 },
        { id: "garlic", qty: 1 },
        { id: "sesameOil", qty: 0.5 },
        { id: "vegOil", qty: 1 },
      ],
    },
    {
      id: "sheet-sausage",
      name: "Sheet-pan sausage, potato & cabbage",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 40,
      cuisines: ["american", "comfort"],
      proteins: ["pork"],
      ingredients: [
        { id: "sausage", qty: 1 },
        { id: "potato", qty: 2.5 },
        { id: "cabbage", qty: 1 },
        { id: "onion", qty: 1 },
        { id: "vegOil", qty: 1.5 },
        { id: "paprika", qty: 0.2 },
        { id: "salt", qty: 0.1 },
      ],
    },
    {
      id: "potato-bar",
      name: "Loaded baked potatoes",
      meal: "dinner",
      yield: 3,
      leftover: "lunch",
      minutes: 50,
      cuisines: ["american", "comfort"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "potato", qty: 3 },
        { id: "cheddar", qty: 0.4 },
        { id: "blackBeans", qty: 1 },
        { id: "broccoli", qty: 0.75 },
        { id: "salsa", qty: 8 },
        { id: "salt", qty: 0.1 },
      ],
    },
    {
      id: "tuna-pasta",
      name: "Tuna lemon pasta",
      meal: "dinner",
      yield: 3,
      leftover: "lunch",
      minutes: 20,
      cuisines: ["italian", "mediterranean"],
      proteins: ["fish"],
      ingredients: [
        { id: "pasta", qty: 0.75 },
        { id: "tuna", qty: 2 },
        { id: "lemon", qty: 2 },
        { id: "oliveOil", qty: 1.5 },
        { id: "garlic", qty: 1 },
        { id: "spinach", qty: 5 },
        { id: "blackPepper", qty: 0.05 },
      ],
    },
    {
      id: "greek-chicken",
      name: "Lemon garlic chicken & rice",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 40,
      cuisines: ["mediterranean"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenThigh", qty: 1.75 },
        { id: "rice", qty: 1 },
        { id: "lemon", qty: 2 },
        { id: "garlic", qty: 1 },
        { id: "oliveOil", qty: 1.5 },
        { id: "spinach", qty: 8 },
        { id: "italian", qty: 0.15 },
      ],
    },
    {
      id: "bean-quesadilla",
      name: "Crispy bean quesadillas",
      meal: "lunch",
      yield: 4,
      leftover: "lunch",
      minutes: 20,
      cuisines: ["mexican"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "tortillas", qty: 1 },
        { id: "blackBeans", qty: 2 },
        { id: "cheddar", qty: 0.5 },
        { id: "salsa", qty: 8 },
        { id: "onion", qty: 1 },
        { id: "cumin", qty: 0.1 },
      ],
    },
    {
      id: "tuna-sandwich",
      name: "Tuna sandwiches",
      meal: "lunch",
      yield: 4,
      leftover: "lunch",
      minutes: 10,
      cuisines: ["american"],
      proteins: ["fish"],
      ingredients: [
        { id: "tuna", qty: 3 },
        { id: "bread", qty: 1 },
        { id: "celery", qty: 1 },
        { id: "onion", qty: 0.4 },
        { id: "lemon", qty: 1 },
      ],
    },
    {
      id: "hummus-bowls",
      name: "Chickpea rice bowls",
      meal: "lunch",
      yield: 4,
      leftover: "lunch",
      minutes: 25,
      cuisines: ["mediterranean"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "chickpeas", qty: 2 },
        { id: "rice", qty: 0.75 },
        { id: "spinach", qty: 8 },
        { id: "lemon", qty: 2 },
        { id: "oliveOil", qty: 1.5 },
        { id: "garlic", qty: 1 },
        { id: "cumin", qty: 0.15 },
      ],
    },
    {
      id: "peanut-noodles",
      name: "Peanut noodles",
      meal: "lunch",
      yield: 3,
      leftover: "lunch",
      minutes: 20,
      cuisines: ["asian"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "pasta", qty: 0.75 },
        { id: "peanutButter", qty: 4 },
        { id: "soy", qty: 2 },
        { id: "carrot", qty: 0.5 },
        { id: "cabbage", qty: 0.4 },
        { id: "garlic", qty: 1 },
        { id: "hotSauce", qty: 0.5 },
      ],
    },
    {
      id: "rice-beans",
      name: "Rice, beans & salsa",
      meal: "dinner",
      yield: 4,
      leftover: "lunch",
      minutes: 25,
      cuisines: ["mexican", "american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "rice", qty: 1.25 },
        { id: "blackBeans", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "salsa", qty: 8 },
        { id: "cumin", qty: 0.15 },
        { id: "vegOil", qty: 1 },
      ],
    },
    {
      id: "tomato-soup-melt",
      name: "Tomato soup & cheese toasts",
      meal: "dinner",
      yield: 3,
      leftover: "lunch",
      minutes: 25,
      cuisines: ["american", "comfort"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "cannedTomato", qty: 3 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "broth", qty: 16 },
        { id: "bread", qty: 1 },
        { id: "cheddar", qty: 0.35 },
        { id: "oliveOil", qty: 1 },
        { id: "italian", qty: 0.15 },
      ],
    },
  ];

  RECIPES.forEach((recipe) => {
    recipe.ingredients = recipe.ingredients.filter((row) => INGREDIENTS[row.id]);
  });

  return { STORES, INGREDIENTS, PANTRY_GROUPS, RECIPES };
})();
