window.CK_DATA = (() => {
  const p = (bargain, value, harbor, shoprite, grove) => ({
    bargain,
    value,
    harbor,
    shoprite,
    grove,
  });

  const STORES = [
    {
      id: "bargain",
      name: "Aldi",
      kind: "Discount grocer",
      mapsQuery: "Aldi",
      blurb: "Usually the lowest on staples, produce, and store-brand proteins.",
    },
    {
      id: "value",
      name: "Walmart",
      kind: "Big-box grocery",
      mapsQuery: "Walmart Supercenter grocery",
      blurb: "Broadest shelf. Strong on eggs, bacon, and name brands.",
    },
    {
      id: "harbor",
      name: "Kroger",
      kind: "Neighborhood supermarket",
      mapsQuery: "Kroger",
      blurb: "Weekly sales and a full meat counter.",
    },
    {
      id: "shoprite",
      name: "ShopRite",
      kind: "Northeast supermarket",
      mapsQuery: "ShopRite",
      blurb: "Bowl & Basket store brand and big weekly ads. Typical Northeast prices.",
    },
    {
      id: "grove",
      name: "Whole Foods",
      kind: "Premium grocer",
      mapsQuery: "Whole Foods Market",
      blurb: "Highest everyday prices. Use only if this is your store.",
    },
  ];

  const INGREDIENTS = {
    oats: { name: "Rolled oats", unit: "lb", pack: 1, category: "Grains", pantry: "staples", prices: p(1.49, 1.78, 2.19, 2.29, 3.99) },
    rice: { name: "Long-grain rice", unit: "lb", pack: 1, category: "Grains", pantry: "staples", prices: p(0.89, 1.08, 1.39, 1.29, 2.79) },
    pasta: { name: "Dry pasta", unit: "lb", pack: 1, category: "Grains", pantry: "staples", prices: p(1.15, 1.28, 1.49, 1.39, 2.29) },
    bread: { name: "Sandwich bread", unit: "loaf", pack: 1, category: "Grains", prices: p(1.59, 1.78, 2.69, 2.79, 4.49) },
    tortillas: { name: "Flour tortillas", unit: "pack", pack: 1, category: "Grains", prices: p(1.79, 2.18, 2.69, 2.49, 3.99) },
    flour: { name: "All-purpose flour", unit: "lb", pack: 2, category: "Grains", pantry: "staples", prices: p(0.5, 0.58, 0.72, 0.69, 1.19) },
    eggs: { name: "Eggs", unit: "each", pack: 12, category: "Dairy", pantry: "fridge", prices: p(0.21, 0.19, 0.25, 0.23, 0.5) },
    milk: { name: "Milk", unit: "gal", pack: 1, category: "Dairy", pantry: "fridge", prices: p(2.89, 3.38, 3.69, 3.79, 5.99) },
    yogurt: { name: "Plain yogurt", unit: "oz", pack: 32, category: "Dairy", prices: p(0.09, 0.1, 0.13, 0.12, 0.19) },
    cheddar: { name: "Cheddar", unit: "lb", pack: 0.5, category: "Dairy", prices: p(4.48, 4.96, 5.48, 5.28, 8.99) },
    mozzarella: { name: "Mozzarella", unit: "lb", pack: 0.5, category: "Dairy", prices: p(4.98, 5.48, 5.98, 5.78, 8.99) },
    parmesan: { name: "Parmesan", unit: "lb", pack: 0.5, category: "Dairy", prices: p(7.98, 8.48, 9.48, 8.98, 14.99) },
    sourCream: { name: "Sour cream", unit: "oz", pack: 16, category: "Dairy", prices: p(0.14, 0.16, 0.18, 0.17, 0.28) },
    butter: { name: "Butter", unit: "lb", pack: 1, category: "Dairy", pantry: "oils", prices: p(3.75, 3.96, 4.49, 4.69, 6.99) },
    chickenThigh: { name: "Chicken thighs", unit: "lb", pack: 1, category: "Meat", prices: p(1.99, 2.29, 2.69, 2.79, 5.49) },
    chickenBreast: { name: "Chicken breast", unit: "lb", pack: 1, category: "Meat", prices: p(2.99, 2.89, 3.49, 3.29, 7.99) },
    groundBeef: { name: "Ground beef 85%", unit: "lb", pack: 1, category: "Meat", prices: p(5.29, 5.97, 6.49, 6.29, 8.99) },
    groundTurkey: { name: "Ground turkey", unit: "lb", pack: 1, category: "Meat", prices: p(3.49, 3.98, 4.29, 4.49, 6.99) },
    sausage: { name: "Smoked sausage", unit: "lb", pack: 1, category: "Meat", prices: p(3.29, 3.48, 3.99, 3.89, 6.49) },
    bacon: { name: "Bacon", unit: "lb", pack: 1, category: "Meat", prices: p(5.49, 5.29, 5.99, 5.79, 8.99) },
    pork: { name: "Pork", unit: "lb", pack: 1, category: "Meat", prices: p(3.29, 3.48, 3.99, 3.79, 6.49) },
    lamb: { name: "Lamb", unit: "lb", pack: 1, category: "Meat", prices: p(7.99, 8.48, 9.49, 9.29, 14.99) },
    tuna: { name: "Canned tuna", unit: "can", pack: 1, category: "Meat", prices: p(0.99, 0.96, 1.29, 1.25, 2.49) },
    shrimp: { name: "Shrimp", unit: "lb", pack: 1, category: "Meat", prices: p(6.99, 7.48, 8.49, 7.99, 12.99) },
    salmon: { name: "Salmon", unit: "lb", pack: 1, category: "Meat", prices: p(8.99, 9.48, 10.99, 10.49, 14.99) },
    tofu: { name: "Tofu", unit: "lb", pack: 1, category: "Meat", prices: p(1.99, 2.18, 2.69, 2.49, 3.49) },
    onion: { name: "Yellow onion", unit: "each", pack: 1, category: "Produce", pantry: "produce", prices: p(0.79, 0.89, 1.09, 1.19, 1.49) },
    garlic: { name: "Garlic head", unit: "each", pack: 1, category: "Produce", pantry: "produce", prices: p(0.59, 0.68, 0.89, 0.79, 1.19) },
    carrot: { name: "Carrots", unit: "lb", pack: 1, category: "Produce", prices: p(0.89, 1.09, 1.29, 1.39, 1.99) },
    celery: { name: "Celery", unit: "bunch", pack: 1, category: "Produce", prices: p(1.49, 1.68, 1.99, 1.89, 2.79) },
    broccoli: { name: "Broccoli", unit: "lb", pack: 1, category: "Produce", prices: p(1.79, 1.98, 2.29, 1.99, 3.49) },
    spinach: { name: "Baby spinach", unit: "oz", pack: 8, category: "Produce", prices: p(0.29, 0.32, 0.36, 0.35, 0.55) },
    pepper: { name: "Bell pepper", unit: "each", pack: 1, category: "Produce", prices: p(0.99, 1.18, 1.49, 1.29, 1.99) },
    tomato: { name: "Tomatoes", unit: "lb", pack: 1, category: "Produce", prices: p(1.69, 1.88, 2.19, 2.29, 3.49) },
    potato: { name: "Russet potatoes", unit: "lb", pack: 1, category: "Produce", prices: p(0.69, 0.77, 0.99, 0.89, 1.69) },
    cabbage: { name: "Green cabbage", unit: "each", pack: 1, category: "Produce", prices: p(1.79, 1.98, 2.49, 2.29, 3.49) },
    banana: { name: "Bananas", unit: "each", pack: 1, category: "Produce", prices: p(0.22, 0.25, 0.32, 0.29, 0.45) },
    apple: { name: "Apples", unit: "each", pack: 1, category: "Produce", prices: p(0.69, 0.79, 0.99, 0.89, 1.49) },
    lemon: { name: "Lemon", unit: "each", pack: 1, category: "Produce", pantry: "produce", prices: p(0.59, 0.69, 0.79, 0.75, 0.99) },
    lime: { name: "Lime", unit: "each", pack: 1, category: "Produce", prices: p(0.39, 0.45, 0.59, 0.49, 0.79) },
    avocado: { name: "Avocado", unit: "each", pack: 1, category: "Produce", prices: p(1.09, 1.18, 1.49, 1.29, 1.99) },
    cucumber: { name: "Cucumber", unit: "each", pack: 1, category: "Produce", prices: p(0.79, 0.88, 1.09, 0.99, 1.49) },
    lettuce: { name: "Lettuce", unit: "each", pack: 1, category: "Produce", prices: p(1.79, 1.97, 2.29, 2.19, 3.49) },
    zucchini: { name: "Zucchini", unit: "each", pack: 1, category: "Produce", prices: p(0.89, 0.99, 1.29, 1.19, 1.79) },
    mushroom: { name: "Mushrooms", unit: "lb", pack: 0.5, category: "Produce", prices: p(3.49, 3.98, 4.49, 4.29, 6.49) },
    ginger: { name: "Fresh ginger", unit: "oz", pack: 4, category: "Produce", prices: p(0.35, 0.42, 0.55, 0.49, 0.79) },
    cannedTomato: { name: "Canned tomatoes", unit: "can", pack: 1, category: "Pantry", pantry: "staples", prices: p(0.99, 1.12, 1.29, 1.19, 2.19) },
    frozenVeg: { name: "Frozen mixed vegetables", unit: "lb", pack: 1, category: "Frozen", prices: p(1.29, 1.48, 1.79, 1.69, 2.99) },
    blackBeans: { name: "Canned black beans", unit: "can", pack: 1, category: "Pantry", pantry: "staples", prices: p(0.89, 0.98, 1.19, 0.99, 1.69) },
    lentils: { name: "Dry lentils", unit: "lb", pack: 1, category: "Pantry", pantry: "staples", prices: p(1.39, 1.58, 1.89, 1.79, 2.69) },
    chickpeas: { name: "Canned chickpeas", unit: "can", pack: 1, category: "Pantry", prices: p(0.89, 0.98, 1.19, 0.99, 1.69) },
    corn: { name: "Canned corn", unit: "can", pack: 1, category: "Pantry", prices: p(0.72, 0.78, 0.99, 0.89, 1.49) },
    coconutMilk: { name: "Coconut milk", unit: "can", pack: 1, category: "Pantry", prices: p(1.49, 1.68, 1.99, 1.89, 2.79) },
    peanutButter: { name: "Peanut butter", unit: "oz", pack: 16, category: "Pantry", pantry: "staples", prices: p(0.14, 0.16, 0.19, 0.18, 0.32) },
    salsa: { name: "Salsa", unit: "oz", pack: 16, category: "Pantry", prices: p(0.12, 0.14, 0.17, 0.16, 0.28) },
    broth: { name: "Chicken broth", unit: "oz", pack: 32, category: "Pantry", prices: p(0.05, 0.06, 0.08, 0.07, 0.14) },
    honey: { name: "Honey", unit: "oz", pack: 12, category: "Pantry", pantry: "staples", prices: p(0.28, 0.32, 0.38, 0.36, 0.55) },
    oliveOil: { name: "Olive oil", unit: "oz", pack: 17, category: "Oils", pantry: "oils", prices: p(0.26, 0.32, 0.38, 0.36, 0.55) },
    vegOil: { name: "Vegetable oil", unit: "oz", pack: 48, category: "Oils", pantry: "oils", prices: p(0.08, 0.09, 0.11, 0.1, 0.18) },
    sesameOil: { name: "Sesame oil", unit: "oz", pack: 5, category: "Oils", pantry: "oils", prices: p(0.55, 0.62, 0.72, 0.69, 0.99) },
    soy: { name: "Soy sauce", unit: "oz", pack: 15, category: "Condiments", pantry: "sauces", prices: p(0.11, 0.13, 0.16, 0.15, 0.26) },
    vinegar: { name: "Vinegar", unit: "oz", pack: 16, category: "Condiments", pantry: "sauces", prices: p(0.08, 0.09, 0.11, 0.1, 0.16) },
    hotSauce: { name: "Hot sauce", unit: "oz", pack: 5, category: "Condiments", pantry: "sauces", prices: p(0.3, 0.34, 0.42, 0.39, 0.6) },
    ketchup: { name: "Ketchup", unit: "oz", pack: 20, category: "Condiments", pantry: "sauces", prices: p(0.1, 0.12, 0.15, 0.14, 0.22) },
    mayo: { name: "Mayonnaise", unit: "oz", pack: 15, category: "Condiments", pantry: "sauces", prices: p(0.16, 0.18, 0.22, 0.2, 0.34) },
    mustard: { name: "Mustard", unit: "oz", pack: 14, category: "Condiments", pantry: "sauces", prices: p(0.12, 0.14, 0.17, 0.16, 0.26) },
    salt: { name: "Salt", unit: "oz", pack: 26, category: "Seasonings", pantry: "seasonings", prices: p(0.04, 0.05, 0.06, 0.06, 0.1) },
    blackPepper: { name: "Black pepper", unit: "oz", pack: 3, category: "Seasonings", pantry: "seasonings", prices: p(0.63, 0.72, 0.89, 0.85, 1.29) },
    garlicPowder: { name: "Garlic powder", unit: "oz", pack: 3, category: "Seasonings", pantry: "seasonings", prices: p(0.45, 0.55, 0.69, 0.65, 1.09) },
    cumin: { name: "Cumin", unit: "oz", pack: 2, category: "Seasonings", pantry: "seasonings", prices: p(0.58, 0.72, 0.89, 0.85, 1.35) },
    chiliPowder: { name: "Chili powder", unit: "oz", pack: 3, category: "Seasonings", pantry: "seasonings", prices: p(0.42, 0.52, 0.65, 0.62, 0.99) },
    paprika: { name: "Paprika", unit: "oz", pack: 2, category: "Seasonings", pantry: "seasonings", prices: p(0.52, 0.65, 0.79, 0.75, 1.19) },
    italian: { name: "Italian seasoning", unit: "oz", pack: 1, category: "Seasonings", pantry: "seasonings", prices: p(0.85, 1.05, 1.29, 1.19, 1.79) },
    cinnamon: { name: "Cinnamon", unit: "oz", pack: 2, category: "Seasonings", pantry: "seasonings", prices: p(0.48, 0.62, 0.79, 0.75, 1.19) },
    sugar: { name: "Sugar", unit: "lb", pack: 4, category: "Pantry", pantry: "staples", prices: p(0.62, 0.72, 0.85, 0.79, 1.39) },
  };

  const PANTRY_GROUPS = [
    {
      id: "seasonings",
      title: "Seasonings",
      items: ["salt", "blackPepper", "garlicPowder", "cumin", "chiliPowder", "paprika", "italian", "cinnamon"],
    },
    {
      id: "oils",
      title: "Oils & fats",
      items: ["oliveOil", "vegOil", "sesameOil", "butter"],
    },
    {
      id: "sauces",
      title: "Sauces",
      items: ["soy", "vinegar", "hotSauce", "ketchup", "mayo", "mustard"],
    },
    {
      id: "staples",
      title: "Dry staples",
      items: ["oats", "rice", "pasta", "flour", "sugar", "cannedTomato", "blackBeans", "lentils", "peanutButter", "honey"],
    },
    {
      id: "produce",
      title: "Already in the kitchen",
      items: ["onion", "garlic", "lemon"],
    },
    {
      id: "fridge",
      title: "Fridge staples",
      items: ["eggs", "milk"],
    },
  ];

  const RECIPES = [
    {
      id: "oat-bowls",
      name: "Banana oat bowls",
      meal: "breakfast",
      yield: 7,
      minutes: 10,
      cuisines: ["american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "oats", qty: 1.5 },
        { id: "banana", qty: 7 },
        { id: "peanutButter", qty: 7 },
        { id: "cinnamon", qty: 0.2 },
        { id: "milk", qty: 0.25 },
      ],
      instructions: [
        "Add oats and milk to a pot or microwave-safe bowl.",
        "Cook until creamy, 3–5 minutes.",
        "Top with sliced banana, peanut butter, and cinnamon.",
      ],
    },
    {
      id: "egg-toast",
      name: "Eggs on toast",
      meal: "breakfast",
      yield: 7,
      minutes: 15,
      cuisines: ["american"],
      proteins: ["eggs"],
      ingredients: [
        { id: "eggs", qty: 14 },
        { id: "bread", qty: 1 },
        { id: "butter", qty: 0.15 },
        { id: "salt", qty: 0.1 },
        { id: "blackPepper", qty: 0.05 },
      ],
      instructions: [
        "Toast the bread.",
        "Fry or scramble two eggs per person in butter.",
        "Season with salt and pepper and serve on toast.",
      ],
    },
    {
      id: "yogurt-cups",
      name: "Yogurt, apple & peanut butter",
      meal: "breakfast",
      yield: 7,
      minutes: 5,
      cuisines: ["american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "yogurt", qty: 32 },
        { id: "apple", qty: 7 },
        { id: "peanutButter", qty: 7 },
      ],
      instructions: [
        "Spoon yogurt into bowls.",
        "Top with chopped apple and a swirl of peanut butter.",
      ],
    },
    {
      id: "breakfast-burritos",
      name: "Egg & bean breakfast burritos",
      meal: "breakfast",
      yield: 7,
      minutes: 30,
      cuisines: ["mexican"],
      proteins: ["eggs", "vegetarian"],
      ingredients: [
        { id: "eggs", qty: 10 },
        { id: "blackBeans", qty: 2 },
        { id: "tortillas", qty: 1 },
        { id: "cheddar", qty: 0.35 },
        { id: "salsa", qty: 8 },
        { id: "onion", qty: 1 },
      ],
      instructions: [
        "Warm the beans with chopped onion.",
        "Scramble the eggs and stir in cheese.",
        "Fill tortillas with eggs, beans, and salsa.",
        "Wrap and eat now, or chill and reheat through the week.",
      ],
    },
    {
      id: "avocado-toast",
      name: "Avocado toast with egg",
      meal: "breakfast",
      yield: 5,
      minutes: 12,
      cuisines: ["american", "mediterranean"],
      proteins: ["eggs", "vegetarian"],
      ingredients: [
        { id: "bread", qty: 1 },
        { id: "avocado", qty: 3 },
        { id: "eggs", qty: 5 },
        { id: "lemon", qty: 1 },
        { id: "salt", qty: 0.08 },
        { id: "hotSauce", qty: 0.4 },
      ],
      instructions: [
        "Toast the bread and mash avocado with lemon and salt.",
        "Fry or poach one egg per toast.",
        "Spread avocado, add the egg, and finish with hot sauce.",
      ],
    },
    {
      id: "chili",
      name: "Beef & bean chili",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 50,
      cuisines: ["american", "mexican"],
      proteins: ["beef"],
      ingredients: [
        { id: "groundBeef", qty: 1 },
        { id: "blackBeans", qty: 2 },
        { id: "cannedTomato", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "chiliPowder", qty: 0.4 },
        { id: "cumin", qty: 0.2 },
        { id: "rice", qty: 0.75 },
      ],
      instructions: [
        "Brown the beef with onion and garlic.",
        "Stir in beans, tomatoes, chili powder, and cumin.",
        "Simmer 25–30 minutes.",
        "Serve over rice. Pack leftovers for lunch.",
      ],
    },
    {
      id: "turkey-chili",
      name: "Turkey chili",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 45,
      cuisines: ["american"],
      proteins: ["chicken"],
      ingredients: [
        { id: "groundTurkey", qty: 1 },
        { id: "blackBeans", qty: 2 },
        { id: "cannedTomato", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "chiliPowder", qty: 0.4 },
        { id: "cumin", qty: 0.2 },
        { id: "rice", qty: 0.75 },
      ],
      instructions: [
        "Cook turkey and onion until browned.",
        "Add beans, tomatoes, and spices.",
        "Simmer 20 minutes and serve over rice.",
      ],
    },
    {
      id: "garlic-chicken-rice",
      name: "Garlic chicken, rice & broccoli",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 35,
      cuisines: ["american"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenThigh", qty: 1.75 },
        { id: "rice", qty: 1 },
        { id: "broccoli", qty: 1.5 },
        { id: "garlic", qty: 1 },
        { id: "oliveOil", qty: 1 },
        { id: "paprika", qty: 0.15 },
        { id: "salt", qty: 0.1 },
      ],
      instructions: [
        "Season chicken with paprika, salt, and garlic.",
        "Sear in olive oil, then finish cooking through.",
        "Steam broccoli and cook rice.",
        "Plate together and save extra portions for lunch.",
      ],
    },
    {
      id: "taco-skillet",
      name: "Chicken taco skillet",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 30,
      cuisines: ["mexican"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenThigh", qty: 1.5 },
        { id: "tortillas", qty: 1 },
        { id: "blackBeans", qty: 1 },
        { id: "salsa", qty: 12 },
        { id: "cheddar", qty: 0.35 },
        { id: "cabbage", qty: 0.4 },
        { id: "cumin", qty: 0.15 },
        { id: "chiliPowder", qty: 0.2 },
      ],
      instructions: [
        "Cook chopped chicken with cumin and chili powder.",
        "Stir in beans and salsa and simmer 8 minutes.",
        "Serve in tortillas with shredded cabbage and cheddar.",
      ],
    },
    {
      id: "pasta-marinara",
      name: "Pasta marinara with spinach",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 25,
      cuisines: ["italian"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "pasta", qty: 1 },
        { id: "cannedTomato", qty: 2 },
        { id: "garlic", qty: 1 },
        { id: "onion", qty: 1 },
        { id: "spinach", qty: 8 },
        { id: "oliveOil", qty: 1.5 },
        { id: "italian", qty: 0.2 },
      ],
      instructions: [
        "Boil pasta.",
        "Simmer onion, garlic, tomatoes, and Italian seasoning.",
        "Wilt in spinach and toss with the pasta.",
      ],
    },
    {
      id: "sausage-pasta",
      name: "Sausage tomato pasta",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 30,
      cuisines: ["italian"],
      proteins: ["pork"],
      ingredients: [
        { id: "sausage", qty: 1 },
        { id: "pasta", qty: 1 },
        { id: "cannedTomato", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "italian", qty: 0.2 },
      ],
      instructions: [
        "Brown sliced sausage with onion and garlic.",
        "Add tomatoes and Italian seasoning.",
        "Toss with cooked pasta.",
      ],
    },
    {
      id: "lentil-curry",
      name: "Lentil curry bowls",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 40,
      cuisines: ["indian", "asian"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "lentils", qty: 1 },
        { id: "rice", qty: 1 },
        { id: "cannedTomato", qty: 1 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "carrot", qty: 0.75 },
        { id: "cumin", qty: 0.2 },
        { id: "vegOil", qty: 1 },
        { id: "coconutMilk", qty: 1 },
      ],
      instructions: [
        "Sauté onion, garlic, and carrot in oil.",
        "Add lentils, tomatoes, cumin, coconut milk, and water.",
        "Simmer until lentils are tender.",
        "Serve over rice.",
      ],
    },
    {
      id: "stir-fry",
      name: "Veggie stir-fry with eggs",
      meal: "dinner",
      leftover: "lunch",
      yield: 3,
      minutes: 20,
      cuisines: ["asian"],
      proteins: ["eggs", "vegetarian"],
      ingredients: [
        { id: "rice", qty: 0.75 },
        { id: "frozenVeg", qty: 1.5 },
        { id: "eggs", qty: 6 },
        { id: "soy", qty: 2 },
        { id: "garlic", qty: 1 },
        { id: "sesameOil", qty: 0.5 },
        { id: "vegOil", qty: 1 },
      ],
      instructions: [
        "Cook rice.",
        "Stir-fry vegetables and garlic in oil.",
        "Push aside, scramble the eggs, then toss with soy and sesame oil.",
      ],
    },
    {
      id: "sheet-sausage",
      name: "Sheet-pan sausage, potato & cabbage",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 40,
      cuisines: ["american"],
      proteins: ["pork"],
      ingredients: [
        { id: "sausage", qty: 1 },
        { id: "potato", qty: 2.5 },
        { id: "cabbage", qty: 1 },
        { id: "onion", qty: 1 },
        { id: "vegOil", qty: 1.5 },
        { id: "paprika", qty: 0.2 },
        { id: "salt", qty: 0.1 },
      ],
      instructions: [
        "Heat the oven to 425°F.",
        "Toss sausage, potatoes, cabbage, and onion with oil and paprika.",
        "Roast 30–35 minutes, stirring once.",
      ],
    },
    {
      id: "potato-bar",
      name: "Loaded baked potatoes",
      meal: "dinner",
      leftover: "lunch",
      yield: 3,
      minutes: 50,
      cuisines: ["american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "potato", qty: 3 },
        { id: "cheddar", qty: 0.4 },
        { id: "blackBeans", qty: 1 },
        { id: "broccoli", qty: 0.75 },
        { id: "salsa", qty: 8 },
        { id: "salt", qty: 0.1 },
      ],
      instructions: [
        "Bake potatoes at 400°F until tender, about 45 minutes.",
        "Steam broccoli and warm the beans.",
        "Split potatoes and load with cheese, beans, broccoli, and salsa.",
      ],
    },
    {
      id: "tuna-pasta",
      name: "Tuna lemon pasta",
      meal: "dinner",
      leftover: "lunch",
      yield: 3,
      minutes: 20,
      cuisines: ["italian", "mediterranean"],
      proteins: ["fish"],
      ingredients: [
        { id: "pasta", qty: 0.75 },
        { id: "tuna", qty: 2 },
        { id: "lemon", qty: 2 },
        { id: "oliveOil", qty: 1.5 },
        { id: "garlic", qty: 1 },
        { id: "spinach", qty: 5 },
        { id: "blackPepper", qty: 0.05 },
      ],
      instructions: [
        "Cook pasta.",
        "Warm garlic in olive oil, then toss with tuna, lemon, spinach, and pasta.",
      ],
    },
    {
      id: "greek-chicken",
      name: "Lemon garlic chicken & rice",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 40,
      cuisines: ["mediterranean"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenThigh", qty: 1.75 },
        { id: "rice", qty: 1 },
        { id: "lemon", qty: 2 },
        { id: "garlic", qty: 1 },
        { id: "oliveOil", qty: 1.5 },
        { id: "spinach", qty: 8 },
        { id: "italian", qty: 0.15 },
      ],
      instructions: [
        "Marinate chicken with lemon, garlic, oil, and seasoning.",
        "Roast or pan-cook until done.",
        "Serve with rice and a handful of spinach.",
      ],
    },
    {
      id: "bean-quesadilla",
      name: "Crispy bean quesadillas",
      meal: "lunch",
      yield: 4,
      minutes: 20,
      cuisines: ["mexican"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "tortillas", qty: 1 },
        { id: "blackBeans", qty: 2 },
        { id: "cheddar", qty: 0.5 },
        { id: "salsa", qty: 8 },
        { id: "onion", qty: 1 },
        { id: "cumin", qty: 0.1 },
      ],
      instructions: [
        "Mash beans with cumin and chopped onion.",
        "Fill tortillas with beans and cheese.",
        "Toast in a dry skillet until crisp. Serve with salsa.",
      ],
    },
    {
      id: "tuna-sandwich",
      name: "Tuna sandwiches",
      meal: "lunch",
      yield: 4,
      minutes: 10,
      cuisines: ["american"],
      proteins: ["fish"],
      ingredients: [
        { id: "tuna", qty: 3 },
        { id: "bread", qty: 1 },
        { id: "celery", qty: 1 },
        { id: "onion", qty: 0.4 },
        { id: "mayo", qty: 3 },
        { id: "lemon", qty: 1 },
      ],
      instructions: [
        "Mix tuna with mayo, chopped celery, onion, and lemon.",
        "Pile onto bread and slice.",
      ],
    },
    {
      id: "hummus-bowls",
      name: "Chickpea rice bowls",
      meal: "lunch",
      yield: 4,
      minutes: 25,
      cuisines: ["mediterranean"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "chickpeas", qty: 2 },
        { id: "rice", qty: 0.75 },
        { id: "spinach", qty: 8 },
        { id: "lemon", qty: 2 },
        { id: "oliveOil", qty: 1.5 },
        { id: "garlic", qty: 1 },
        { id: "cumin", qty: 0.15 },
      ],
      instructions: [
        "Warm chickpeas with garlic, cumin, lemon, and oil.",
        "Spoon over rice and spinach.",
      ],
    },
    {
      id: "peanut-noodles",
      name: "Peanut noodles",
      meal: "lunch",
      yield: 3,
      minutes: 20,
      cuisines: ["asian"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "pasta", qty: 0.75 },
        { id: "peanutButter", qty: 4 },
        { id: "soy", qty: 2 },
        { id: "carrot", qty: 0.5 },
        { id: "cabbage", qty: 0.4 },
        { id: "garlic", qty: 1 },
        { id: "hotSauce", qty: 0.5 },
      ],
      instructions: [
        "Cook noodles.",
        "Whisk peanut butter, soy, garlic, and hot sauce with a splash of hot water.",
        "Toss with shredded carrot and cabbage.",
      ],
    },
    {
      id: "rice-beans",
      name: "Rice, beans & salsa",
      meal: "dinner",
      leftover: "lunch",
      yield: 4,
      minutes: 25,
      cuisines: ["mexican", "american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "rice", qty: 1.25 },
        { id: "blackBeans", qty: 2 },
        { id: "onion", qty: 1 },
        { id: "salsa", qty: 8 },
        { id: "cumin", qty: 0.15 },
        { id: "vegOil", qty: 1 },
      ],
      instructions: [
        "Cook rice.",
        "Warm beans with onion, cumin, and oil.",
        "Serve with salsa.",
      ],
    },
    {
      id: "tomato-soup-melt",
      name: "Tomato soup & cheese toasts",
      meal: "dinner",
      leftover: "lunch",
      yield: 3,
      minutes: 25,
      cuisines: ["american"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "cannedTomato", qty: 3 },
        { id: "onion", qty: 1 },
        { id: "garlic", qty: 1 },
        { id: "broth", qty: 16 },
        { id: "bread", qty: 1 },
        { id: "cheddar", qty: 0.35 },
        { id: "oliveOil", qty: 1 },
        { id: "italian", qty: 0.15 },
      ],
      instructions: [
        "Simmer onion, garlic, tomatoes, broth, and seasoning.",
        "Blend if you want it smooth.",
        "Broil cheddar on toast and serve with the soup.",
      ],
    },
    {
      id: "chicken-salad",
      name: "Chicken salad lettuce cups",
      meal: "lunch",
      yield: 4,
      minutes: 20,
      cuisines: ["american"],
      proteins: ["chicken"],
      ingredients: [
        { id: "chickenBreast", qty: 1 },
        { id: "mayo", qty: 3 },
        { id: "celery", qty: 1 },
        { id: "apple", qty: 1 },
        { id: "lettuce", qty: 1 },
        { id: "mustard", qty: 0.5 },
        { id: "salt", qty: 0.05 },
      ],
      instructions: [
        "Poach or use leftover chicken and chop it.",
        "Mix with mayo, mustard, celery, and apple.",
        "Spoon into lettuce leaves.",
      ],
    },
    {
      id: "greek-lunch-box",
      name: "Greek snack boxes",
      meal: "lunch",
      yield: 4,
      minutes: 15,
      cuisines: ["mediterranean"],
      proteins: ["vegetarian"],
      ingredients: [
        { id: "chickpeas", qty: 1 },
        { id: "cucumber", qty: 2 },
        { id: "tomato", qty: 1 },
        { id: "yogurt", qty: 16 },
        { id: "lemon", qty: 1 },
        { id: "oliveOil", qty: 1 },
      ],
      instructions: [
        "Stir yogurt with lemon and a pinch of salt for a quick dip.",
        "Pack with chickpeas, cucumber, and tomatoes.",
        "Drizzle oil over the vegetables.",
      ],
    },
  ];

  const RECIPE_META = {
    "oat-bowls": { image: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=70", kcal: 360, protein: 12, carbs: 54, fat: 11, tag: "Speedy Meals" },
    "egg-toast": { image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=800&q=70", kcal: 320, protein: 18, carbs: 28, fat: 14, tag: "Speedy Meals" },
    "yogurt-cups": { image: "https://images.unsplash.com/photo-1488477182946-bb92d543bac5?auto=format&fit=crop&w=800&q=70", kcal: 290, protein: 16, carbs: 32, fat: 10, tag: "Speedy Meals" },
    "breakfast-burritos": { image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=70", kcal: 410, protein: 22, carbs: 38, fat: 18, tag: "High Protein" },
    "avocado-toast": { image: "https://images.unsplash.com/photo-1541519227354-08fa9d52bd26?auto=format&fit=crop&w=800&q=70", kcal: 380, protein: 16, carbs: 28, fat: 22, tag: "Speedy Meals" },
    chili: { image: "https://images.unsplash.com/photo-1515516969-d4008cc6241a?auto=format&fit=crop&w=800&q=70", kcal: 480, protein: 32, carbs: 42, fat: 18, tag: "Batch Cook" },
    "turkey-chili": { image: "https://images.unsplash.com/photo-1547592166-23acba8896fb?auto=format&fit=crop&w=800&q=70", kcal: 430, protein: 34, carbs: 40, fat: 12, tag: "High Protein" },
    "garlic-chicken-rice": { image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=70", kcal: 520, protein: 38, carbs: 48, fat: 16, tag: "High Protein" },
    "taco-skillet": { image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=70", kcal: 490, protein: 36, carbs: 44, fat: 18, tag: "Speedy Meals" },
    "pasta-marinara": { image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a7?auto=format&fit=crop&w=800&q=70", kcal: 440, protein: 14, carbs: 68, fat: 12, tag: "Speedy Meals" },
    "sausage-pasta": { image: "https://images.unsplash.com/photo-1551183053-bf2f2fb1d8e1?auto=format&fit=crop&w=800&q=70", kcal: 560, protein: 24, carbs: 62, fat: 22, tag: "Comfort" },
    "lentil-curry": { image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=800&q=70", kcal: 410, protein: 20, carbs: 62, fat: 8, tag: "Gut Friendly" },
    "stir-fry": { image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=70", kcal: 390, protein: 18, carbs: 48, fat: 12, tag: "Speedy Meals" },
    "sheet-sausage": { image: "https://images.unsplash.com/photo-1529042410759-befb0e6e2093?auto=format&fit=crop&w=800&q=70", kcal: 540, protein: 26, carbs: 38, fat: 28, tag: "Sheet Pan" },
    "potato-bar": { image: "https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&w=800&q=70", kcal: 470, protein: 16, carbs: 64, fat: 16, tag: "Comfort" },
    "tuna-pasta": { image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=70", kcal: 430, protein: 28, carbs: 52, fat: 12, tag: "Speedy Meals" },
    "greek-chicken": { image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=70", kcal: 500, protein: 40, carbs: 42, fat: 16, tag: "High Protein" },
    "bean-quesadilla": { image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=800&q=70", kcal: 420, protein: 18, carbs: 46, fat: 18, tag: "Speedy Meals" },
    "tuna-sandwich": { image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=800&q=70", kcal: 340, protein: 26, carbs: 32, fat: 10, tag: "Speedy Meals" },
    "hummus-bowls": { image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=70", kcal: 380, protein: 14, carbs: 52, fat: 12, tag: "Gut Friendly" },
    "peanut-noodles": { image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=70", kcal: 520, protein: 18, carbs: 64, fat: 20, tag: "Speedy Meals" },
    "rice-beans": { image: "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=800&q=70", kcal: 390, protein: 16, carbs: 68, fat: 6, tag: "Gut Friendly" },
    "tomato-soup-melt": { image: "https://images.unsplash.com/photo-1547592166-23acba8896fb?auto=format&fit=crop&w=800&q=70", kcal: 410, protein: 14, carbs: 46, fat: 16, tag: "Comfort" },
    "chicken-salad": { image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=70", kcal: 360, protein: 28, carbs: 14, fat: 18, tag: "High Protein" },
    "greek-lunch-box": { image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=70", kcal: 320, protein: 14, carbs: 36, fat: 12, tag: "Packable" },
  };

  RECIPES.forEach((recipe) => {
    recipe.ingredients = recipe.ingredients.filter((row) => INGREDIENTS[row.id]);
    Object.assign(recipe, RECIPE_META[recipe.id] || {});
    if (!recipe.tag) recipe.tag = recipe.minutes <= 25 ? "Speedy Meals" : "Weeknight";
    recipe.source = recipe.source || "local";
  });

  function addIngredient(id, item) {
    if (!INGREDIENTS[id]) INGREDIENTS[id] = item;
    return INGREDIENTS[id];
  }

  function addRecipes(list) {
    const seen = new Set(RECIPES.map((recipe) => recipe.id));
    for (const recipe of list || []) {
      if (!recipe || seen.has(recipe.id)) continue;
      RECIPES.push(recipe);
      seen.add(recipe.id);
    }
    return RECIPES;
  }

  return { STORES, INGREDIENTS, PANTRY_GROUPS, RECIPES, addIngredient, addRecipes };
})();
